# Generated by Django 4.2.7 on 2023-11-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                (
                    "language",
                    models.CharField(choices=[("py", "Python"), ("ru", "Rust")]),
                ),
                ("description", models.TextField()),
            ],
        ),
    ]
